// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 기본설정
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // 특정 폴더 > 카테고리 
  // But you can create a sidebar manually
};

module.exports = sidebars;