// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '문서 시작하기',
      collapsible: false,
      link: {
        type: 'generated-index',
        title: 'Docs',
        description: 'All Docs',
        slug: '/', 
      },
      items: [
        {
          type: 'category',
          label: '개발 기록',
          collapsible: false,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'dev-log'}],
        },
        {
          type: 'category',
          label: '프론트엔드 로드맵 2025',
          collapsible: false,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'fe-roadmap'}],
        },
        {
          type: 'category',
          label: '프레임워크',
          collapsible: false,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'framework'}],
        },
        {
          type: 'category',
          label: 'JS 심화',
          collapsible: false,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'js-deep-dive'}],
        },
        {
          type: 'category',
          label: '프로그래머스',
          collapsible: false,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'programmers'}],
        },
      ],
    },
  ],
};

module.exports = sidebars;

